apiVersion: v1
kind: Service
metadata:
  name: house-price-prediction-service
  namespace: house-price-namespace  # Specify your namespace here
spec:
  selector:
    app: house-price-prediction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5005
  type: LoadBalancer
